XAMPPRocky/tokei

src/main.rs
See: http://julialang.org/. The file extension is `.jl`, single line comments starts with `#` and multi-line comments are enclosed by `#=` and `=#`.
=> Add Julia language

src/language.rs, src/main.rs, src/stats.rs
Most users are more concerned about code lines than comments or blanks.
=> Prints code lines before comments and blanks

src/fsutil.rs
Tests weren't updated to include the correct number of parameters when has_trailing_comments was updated (c5750f9).
nested=true uses the original, pre-change codepath for the tests.
=> Fixed parameter count mismatch.

src/main.rs.in
Currently (before this commit) those languages' code lines are just ignored by mistake.
=> fix for no-comment languages: Json, Markdown, Text

README.md
I'm not entirely happy with the wording but wanted to avoid using terms like “match” to avoid giving the impression that things like regular expressions or shell globs were supported.
=> Document that `--exclude` accepts a list of values

src/lib/language/languages.rs
Clojure - Removed #
Forth   - ( Comment) style comments need a space after the opening paren
Haskell - Added multiline comment style {- Block comment -}
Jai     - Has nested block comments
Julia   - Has nested block comments
Kotlin  - Has nested block comments
Pascal  - Pascal should be multiline from { or (* to } or *)
Perl    - Perl5 and earlier for multiline comments need =pod to =cut.
Perl6 will be different but as it is not finished I'm not going
to add it.
Python  - Python can use """ or ''' for comments
Swift   - Has nested block comments
The is_fortran code was editted by rustfmt.
=> Made a series of modifications to the languages comments:

CONTRIBUTORS.md, Cargo.toml, src/lib/language/languages.rs
Sorry about the last branch, I forgot I made the in github edit, and couldn't figure out what was wrong.
In response to the Php strings, they have a new string type in Php 5.
<<<EOD
Example of string
spanning multiple lines
using heredoc syntax.
EOD;
<<< Starts the comment, and then gets a variable name, and doesn't end until that variable name comes up again.
=> Fixes issue #52

src/lib/language/language_type.rs, src/lib/language/languages.rs
TCL is also known as [Tool Command Language](https://fr.wikipedia.org/wiki/Tool_Command_Language).
Example:
```
$ time target/release/tokei ~/ws -s code
TCL                 11232     14295483     11399104      1071421      1824958
Plain Text             92        69131        69131            0            0
Python                193        36349        28551         2123         5675
JSON                   32        15192        15192            0            0
XML                   103        15666        15065            0          601
Ruby …
```
=> support tcl

README.md, src/lib/language/language_type.rs, src/lib/language/languages.rs, src/lib/utils/multi_line.rs
This PR adds support for [Lean](https://leanprover.github.io/) source files.
Futhermore I have slightly modified the handling of nested single-line comments.  In at least Haskell and C  (and also Lean) line comments are ignored if they occur inside a multi-line comment.  For example the following programs both work:
```haskell
{- -- -}
main = putStrLn "Hello, world!"
```
```c
/* // */
#include <stdio.h>
int main(int argc, char **argv) { printf("Hello, world!\n"); return 0; }
```
I don't know if any other language handles this differently.
=> Add support for lean

src/lib/language/language_type.rs, src/lib/language/languages.rs
This PR adds support for Elm language. 
I just copy-pasted haskell's comment style, it's right for Elm's syntax, hope it's right from tokei's point.
=> Add support for elm

cli.yml
```
Tokei 4.3.0
Aaron P. <theaaronepower@gmail.com>
Count Code, Quickly.
USAGE:
Tokei [FLAGS] [OPTIONS] <input>...
FLAGS:
-f, --files        Will print out statistics on individual files.
-h, --help         Prints help information
-l, --languages    Prints out supported languages and their extensions.
-V, --version      Prints version information
-v                 Set verbose output level: 1 for File IO errors 2: for unknown extensions
^^^^^^^^^
|<---------------- No long name
```
=> long verbose arg name

src/lib/utils/fs.rs
This fixes multiple issues. Before this commit, a directory with
a known file extension in its name would be added to the list of
"files" to open and read from. Another issue occurred with broken
symbolic links being added to the files list.
=> Only add regular files to path list

src/main.rs
At the moment if you try to output in a particular format and forgot to compile with that feature, the program will just panic.
```
$ tokei src --output json
thread 'main' panicked at 'This version of tokei was compiled without any serialization
formats, to enable serialization, reinstall tokei with the features flag.
cargo install tokei --features all
', /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/tokei-4.4.0/src/main.rs:292
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Although the error message tells you exactly what the problem is and how to fix it, it would still be a lot nicer in terms of end user experience to print the error message to stderr and then exit. Normally when I see that a program has panicked it's because of a bug or an error which can't be …
=> Exit gracefully instead of panicking when using a feature that isn't compiled in

languages.json
It is more accurate to not consider bash and sh to be the same.  Bash is
a superset of sh. Same goes for tcsh, zsh, fish, rc, es, etc.
=> Differentiate between bash and sh

cli.yml, src/main.rs
As defined in `cli.yml`, `--languages` conflicts with `<input>`,
but if `<input>` has default value, `--languages` will always conflict,
even if no inputs were specified.
Computation of the default value for `<input>` is now moved to `src/main.rs`,
because it cannot be specified in `cli.yml` along with `--languages`.
I suspect this bug was introduced in commit b7a892f4753d, when default
value for `<input>` was added.
=> fixed `--languages` option always conflicting with input

languages.json
Since Standard ML is equally often if not more referred to as SML, it
makes sense to include "(SML)" in the display name.
=> Extend Standard ML name

Cargo.lock, Cargo.toml
This avoids bringing in another version of `regex` (and it's dependencies).
=> Update `env_logger` to 0.4

src/main.rs
There is no reason *not* to allow multiple exclude values.
Multiple exclude options are processed correctly by [src/main.rs#L54-L55](https://github.com/m1el/tokei/blob/c0cb7427b440307f0ffd73d51992042ac3d392d1/src/main.rs#L54-L55), but clap config doesn't accept multiple exclude options.
This pull request should cover #111.
=> Allow multiple --exclude options

languages.json
Note that, apparenlty, the build script generates an enum variant for each language.
The only way I could get it to compile was by naming the language `Typescript_JSX`.
There should probably be some plumbing to allow setting an additional name that's used for display. 
Fixes #126
=> Add tsx extension for typescript.

README.md, languages.json, tests/data/qml.qml
Adds [QML](https://doc.qt.io/qt-5/qtqml-syntax-basics.html) language support.
=> Add QML support

Cargo.lock, Cargo.toml, src/input.rs, src/main.rs
`eprint!` and `eprintln!` has been introduced on Rust 1.19.0.
They should provide same functionalities as `err!` and `errln!`.
=> Use eprintln!

README.md, languages.json, tests/data/emacs_dev_env.ede, tests/data/emacs_lisp.el, tests/data/org_mode.org, tests/data/srecode.srt
Add support for following file extensions:
- Emacs Lisp (.el)
- Emacs Development Environement (.ede)
- Org mode (.org)
- SRecode (.srt)
=> Add support for .el, .ede, .org and .srt files

languages.json, tests/data/MSBuild.csproj, tests/data/visualbasic.vb
I work on [Roslyn](https://github.com/dotnet/roslyn) and wanted to see how our VB usage compares to c# internally.  With this PR I get the following which seems about right.
```
Batch                  24          270          193           14           63
C Header                1           15           10            1            4
C#                   7956      2559827      2023968       218514       317345
C++                     4          185          135           22           28
F#                      2           96           63           10 …
```
=> Add the visual basic and msbuild language

README.md, languages.json
File formats:
- Property Specification Language (.psl)
- Specman E (.e)
- SPICE netlist (.ckt)
- SystemVerilog (.sv, .svh)
- Verilog (.vg, .vh)
- Verilog Run Argument files (.irunargs, .xrunargs)
_Note that .v files are **the default** for Verilog files, but at the moment that clashes with Coq files. How can that be resolved?_
=> Add support for .psl, .e, .ckt, .sv, .svh, .vg, .vh, .irunargs, .xrunargs

Cargo.lock
Crossbeam 0.2.10 uses the old auto trait syntax and 0.2.12 switched to the new one. Tokei is a part of Rust's test suite and, since it depends on crossbeam 0.2.10, it is currently blocking the following PR, which removes the old auto trait syntax in favor of the new one: https://github.com/rust-lang/rust/pull/46480#issuecomment-355735400
Diff between versions 0.2.10 and 0.2.12: https://github.com/crossbeam-rs/crossbeam/compare/0.2.10...v0.2.12
=> Update crossbeam to 0.2.12

src/input.rs, src/main.rs
Since 8817762d7b8f5cd10886147b828f95d19dc2a80a, build fails with any
features enabled..
```rust
error[E0308]: mismatched types
--> src/main.rs:95:30
|
95 |         match_output(format, &languages);
|                              ^^^^^^^^^^
|                              |
|                              expected struct `tokei::Languages`, found reference
|                              help: consider removing the borrow: `languages`
|
= note: expected type `tokei::Languages`
found type `&tokei::Languages`
```
Problem is that when no features enabled, match_output() doesn't need
to "eat" `tokei::Languages`, but in real version of match_output it
must not be borrowed.
Fixes: https://github.com/Aaronepower/tokei/issues/177
=> fix build with features enabled

src/input.rs, src/language/languages.rs, src/lib.rs, src/main.rs, src/sort.rs
Went a bit deeper on this than planned, I'm trying to work towards having a `--stream-output` option so I can use tokei to just stream me a bunch of filenames with their stats (not interested in the summary) but I got stuck refactoring a bit of stuff as I was trying to understand how the library was working. 
The previous method of handling formats was quite hard to know when you've missed a method if you want to add a new type and it wasn't easy to get the error messages correct. In theory now someone can use tokei as a library and serialize with whatever format they want using the serde traits directly.
I'm probably going to continue onto making changes to the main library but I felt like this was a good point to check in to see if what I've done already would be wanted upstream or not …
=> Refactor how compiled-in serialization formats are handled

README.md, languages.json
Add support for three languages:
- ABAP (.abap)
- COBOL (.cob, .cbl, .ccp, .cobol, .cpy)
- Groovy (.groovy, .grt, .gtpl, .gvy)
=> add support for more languages

README.md
tokei 7.0.0 is in current stable release-18.03
=> README: remove notice about "unstable" being required for Nix/NixOS

README.md
Informs the user that additional dependencies must be installed to use the output features. Without this, the user may think that all serialization formats are included without additional installation.
=> update README.md with how install output features

README.md, languages.json, tests/data/racket.rkt
This PR would add Racket as a supported language for tokei. It's set up as a copy of the Scheme entry, but with the extension changed to `rkt`. The test file is changed to be valid Racket code.
A complication here is that line 17 of the test file _is_ a valid comment, but it comments out the whole s-expression regardless of how many lines it takes up. I don't believe this is currently possible with tokei, and so this PR does not currently count that line as a comment.
=> Add Racket to the supported languages.

CONTRIBUTING.md, languages.json, tests/data/clojure.clj, tests/data/clojurec.cljc, tests/data/clojurescript.cljs
Hello,
I'm trying to contribute support for `cljc` files (which is a normal Clojure that can compile both to `clj` and `cljs`). I've build the project locally with `cargo build`, then ran it with `cargo run /path/to/a/clojure/project` and it does report ClojureC stats.
However I have trouble adding tests. When I run `cargo test` all tests pass but I don't see any Clojure stuff in the output. Here's the output :
```
> cargo test
Finished dev [unoptimized + debuginfo] target(s) in 0.18 secs
Running target/debug/deps/tokei-29cdc45eb9eb5ec5
running 1 test
test utils::fs::test::walker_directory_as_file ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Running target/debug/deps/tokei-026584b8fa7f366d
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; …
```
=> Add support for ClojureC + tests for all Clojure

README.md, languages.json
> A FEN "record" defines a particular game position, all in one text line and using only the ASCII character set. A text file with only FEN data records should have the file extension ".fen"
[FEN on Wikipedia](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation)
Fairly niche, and not code, so I understand perfectly if you opt to close this PR.
You can see an example file [here](https://github.com/DenialAdams/chessatk/blob/master/tests/positions.fen)
Thanks for your work!
=> Add Forsyth-Edwards-Notation (FEN) support

languages.json, tests/data/dreammaker.dm
"Dream Maker" is the language used by the 2000-era engine "BYOND":
https://secure.byond.com/
It's about as awful as the name implies.
=> Adds Dream Maker support.

languages.json, tests/data/edn.edn
[edn](https://github.com/edn-format/edn) is Clojure's data format and is commonly used in the Clojure community. As the mantra goes, code is data 🙏
=> Add support for edn

Cargo.lock, Cargo.toml, src/main.rs, src/stats.rs
This PR implements #160 for the unix family, changing the output width from 79 to the terminal width if it is wider than 79. I pulled in libc as a dependency for the syscall to make. I will implement the windows variant as well, but I wanted to know if it is okay to use the winapi crate for this or if we should define the one or two functions that are required in the `main.rs` ourself.
Also this PR changes the default behaviour. I wasnt sure if this should be an argument or not. If it should be I'd gladly add that as well if you propose a definition for it.
=> Acknowledge terminal width for output on Unix-systems

languages.json, tests/data/liquid.liquid
Adds support for the Liquid template language. See also:
- https://shopify.github.io/liquid/
- https://github.com/Shopify/liquid
Test data file copied from the Liquid project itself, licensed MIT.
https://github.com/Shopify/liquid/blob/master/performance/tests/dropify/collection.liquid
=> Liquid template language support

src/main.rs, src/sort.rs
Allows the `--sort` argument to be case insensitive. Since the column names are capitalized in the output, this makes it a little more natural so that you can actually use the printed column names as the argument to sort.
=> Let --sort argument be case insensitive.

languages.json, tests/data/nqp.nqp, tests/data/perl6.pl6
Perl6 is just slightly different from Perl 5, with the multline comments starting/ending with `=begin` and `=end` instead of `=pod` and `=cut`.
I have not written Not Quite Perl at all, but it is the language that Perl6 is written in and has very similar syntax, and effectively identical comment syntax.
The tests for these are not entirely accurate. Perl6 allows for multiline comments to have a "tag" of sorts, e.g.
```perl6
=begin item match
Documentation for match here
=end item
```
where "item" is the tag. While one would normally include the `=end item` to be part of the multiline comment, tokei only ends at the `=end` token. Is it possible to define regular expressions for multiline comments? I have not looked too closely at the source.
=> Add language rules for Perl6 and its cousin Not Quite Perl

languages.json, tests/data/swig.i
Hi !
I added the definition for SWIG files (Simplified Wrapper and Interface Generator, [http://swig.org/](http://swig.org/)). It's a wrapper generator used to embed C/C++ code in projects written in other languages.
The syntax is normal C/C++ with added annotations (beginning by `%`).
=> Add SWIG support

languages.json
VHDL files could be named with ".vhdl" extension as well as ".vhd"
=> Adding "vhdl" file extension for VHDL files

README.md
I created a project to containerize tokei:
https://hub.docker.com/r/mbologna/docker-tokei
and with this PR I am adding instructions on how to use the container: you don't have to install anything (aisde from Docker) if you follow this method. This is why I added a new "In a container" section in the README.
=> Feat: add Docker container instructions

languages.json, tests/data/rpmspec.spec
I was not 100% sure where to add the code to test said file but am happy to add it to this PR after some guidance if desired.
I work pretty regularly with RPMs and figured this would be helpful for myself and others.
=> Add RPM specfile language

src/main.rs
Thank you for making Tokei! This fixes the following panic by ensuring that `columns` is always wide enough to print the header row:
$ cargo run -- --columns=66
thread 'main' panicked at 'attempt to subtract with overflow',
src/cli_utils.rs:64:17
=> Fix panic when columns < NO_LANG_HEADER_ROW_LEN

README.md
Current link to Nix/NixOS installation instruction doesn't scroll down on both Firefox and Chrome. This PR fixes it.
=> fix link to nix/nixos installation instruction

languages.json
`.tpp` is [frequently](https://github.com/search?utf8=%E2%9C%93&q=tpp+extension%3Atpp&type=Code&ref=advsearch&l=&l=) used for C++ header files which actually contain implementation details (e.g. due to templates or inlining).
Thanks for this useful tool!
=> add .tpp extension to C++

CHANGELOG.md, COMPARISON.md, README.md, languages.json
The "c" in Xcode should be lowercase.
There's a dash in Objective-C and Objective-C++.
=> Fix spelling for Xcode and Objective-C(++)

languages.json
A language that compiles to Lua, ref: https://moonscript.org/. Does not have multi-line comments.
=> Add MoonScript to Languages

languages.json
Can't just skip over the implementation language of God's Holy Temple as written by Terry A. Davis, now can you?
=> Added support for HolyC (language of TempleOS)

languages.json, tests/data/ron.ron
=> Added Rusty Object Notation

README.md
This is the "easy" way to attribute contributors.
Another thought I had was to automatically generate a `CONTRIBUTING.md` if we wanted to embed contributor data in the repository. Overkill IMHO 😄
=> fix contributor link

languages.json
I added `pyw` since it is a valid Python extension.
I can only find two references to this fact in the official python docs (search for "pyw" in these):
https://www.python.org/dev/peps/pep-0397/
https://www.python.org/download/releases/2.4.1/notes/
=> .pyw is a valid Python extension

README.md
- fix markdown heading level for opensuse entry
- rename "Homebrew" to "MacOS (Homebrew)" so STRG+F for "mac" makes this findable
=> readme: fix heading level, rename macos/homebrew

languages.json, tests/data/ftl.ftl
Adds support for the Apache FreeMarker template language with `.ftl`, `.ftlh`, and `.ftlx` as associated file extensions.
=> Add FreeMarker language support

README.md, languages.json, tests/data/gas.S
.asm is generally associated with MASM,NASM,YASM, while .s and .S are
associated with traditionally what is fed into the GNU assembler.
To support this, create two different assembly file types.
=> Split out GNU style assembly

README.md
Started by noting that PowerShell wasn't listed in the README even though it is supported.  Then looked to see what else wasn't in the README based on languages.json.  Turns out a number of languages.  To make this easier to keep up-to-date, I simply grabbed all the language names from the json and replaced the ones in the README.  Some casing  has changed, but it seems that languages.json should be the source of truth which makes keeping the README up-to-date much simpler as well.
=> Updated README.md to reflect support languages

languages.json, src/language/language_type.hbs.rs
Closes #431.
Adds the `shebang_paths` property to languages.json.
Also adds `from_file_extension` and `from_shebang_path` to `LanguageType`, making `from_path` more clear.
=> Fix shebang language detection

languages.json, tests/data/pan.pan
Example output:
~~~~
BASH                    4          442          299           73           70
Batch                  12          749          558           50          141
CSS                     3          406          305           32           69
HTML                    1           56           41            0           15
JavaScript              4         1559         1052          353          154
Markdown                7           95           95            0            0
Pan                  8298       194446       152913        11179 …
=> Add support for the Pan Configuration DSL

languages.json, tests/data/ruby_html.erb
The `.erb` extension has been used over `.rhtml` in Ruby on Rails for over a decade at this point.
=> Add .erb extension for "Ruby HTML"

tests/data/javascript.js, tests/data/typescript.ts
Added Tests for JavaScript and Typescript, covering many of the edge cases. For #63 :smile:
=> Javascript and Typescript tests

README.md, languages.json, tests/data/svelte.svelte
Added support for a Javascript front end framework called [Svelte](https://svelte.dev/). Sadly, it has very similar format to Vue for files so #488 applies to Svelte as well.
Coincidentally I formatted `languages.json` with [prettier](https://github.com/prettier/prettier)
=> Add language Svelte

languages.json, tests/data/html.html
Previously all lines that were `CSS` or `JavaScript` comments were
counted as code, these are now properly counted as comments.
#488 applies to HTML as well :slightly_frowning_face:
=> Fixed HTML counting JS and CSS comments

languages.json
`.csx` is used by [dotnet script](https://github.com/filipw/dotnet-script) for C# scripting.
=> Add .csx extension for C#

README.md
Adds instructions for installing Tokei via [MacPorts](https://www.macports.org)
=> README.md: add instructions for installing via MacPorts

CONTRIBUTING.md, build.rs, languages.json, src/language/language_type.hbs.rs, src/language/syntax.rs, tests/data/cpp.cpp, tests/data/csharp.cs, tests/data/fsharp.fs, tests/data/rust.rs
Closes #330 
Adds support for verbatim strings in `Rust`, `CSharp`, `FSharp`, and `C++`. This should be easy enough to add for any other languages in the future. The only weird case for future contributors, here is that `Python` behaves correctly in the current implementation of Tokei and would behave incorrectly in the case of verbatim strings.
The Rust implementation is fairly naive, ideally `languages.json` would have a regex `/r(#+)"/`, but the dependency on the `regex` crate would add a good chunk to the compile time and would hurt performance, as mentioned in your comment the most common types are implemented here.
I should've seen this coming, `C++` is incredibly annoying for verbatim strings, the syntax of [`"PREFIX()PREFIX"`](stroustrup.com/C++11FAQ.html#UD-literals) where …
=> Verbatim strings

src/config.rs, src/main.rs, src/sort.rs, tokei.example.toml
Closes #548.
Allows to specify the --sort option in a configuration file.
~However as for now the sort option in a configuration file is case sensitive while the cli option is not.~
This is my first PR on this project and I'm a Rust beginner so I would be happy to receive some feedback.
=> Specify the --sort option in the configuration files

languages.json
The correct language name for vim is Vim script, not Vim Script.
=> Fixed the language name Vim Script to Vim script

Cargo.lock, Cargo.toml, src/cli.rs, src/cli_utils.rs, src/lib.rs, src/main.rs, src/stats.rs
Closes #256 and #458 
With the major release migrating #458 completely seemed like more work than starting from scratch as a result of the redesign of the printing system.
Adds command line argument to print numbers with commas, plain, or dots.
For example, dots would result in 1.324.
```text
Tokei Benchmarking Tool
The use of this tool requires tokei, and hyperfine to be installed and available in your PATH variable.
Please enter the path you would like to benchmark:
hyperfine 1.10.0old tokei: tokei 12.0.4 compiled with serialization support: json
Finished release [optimized] target(s) in 0.07s
Benchmark #1: target/release/tokei ../rust
Time (mean ± σ):     115.3 ms ±   2.4 ms    [User: 646.5 ms, System: 192.7 ms]
Range (min … max):   111.6 ms … 121.1 ms    25 runs
Benchmark #2: tokei …
```
=> feat: number formatted printing

languages.json, tests/data/stylus.styl
[Stylus](https://stylus-lang.com/) is a language used to generate CSS, similar to SASS.
=> Add Stylus language

README.md, languages.json, tests/data/Daml.daml
DAML is essentially a dialect of Haskell for the purposes of counting lines.
=> Add definition for DAML

languages.json, tests/data/stan.stan
Stan is a probabilistic programming language. [Example code](https://github.com/TheEconomist/us-potus-model/blob/85be55ae7b0bc68cb155a9ca975e155837eb4851/scripts/model/poll_model_2020.stan).
=> Add Stan language

README.md, languages.json, tests/data/gwion.gw
Here is the PR adding [Gwion](https://github.com/Gwion/Gwion) support.
I suppose it is complete with the edition of `languages.json` and `README.md`, plus a test file.
Let me know if there is anything to change, otherwise feel free to merge.
---
This fixes #657
=> Add support for Gwion

benchmark.sh, ci/build.bash, ci/set_rust_version.bash, ci/test.bash
Fix following ShellCheck warnings.
[SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086): Double quote to prevent globbing and word splitting.
[SC2162](https://github.com/koalaman/shellcheck/wiki/SC2162): read without -r will mangle backslashes
=> ShellCheck on Bash scripts

languages.json, tests/data/fstar.fst
Hi,
FStar allows single-line comments, for now, `tokei` counts only multi-lines one: that PR just fixes that, and adds a single-line comment to the test file.
Thanks :)
=> FStar language: add single-line comments

README.md
Note: Alpine 3.13 has not been released yet, it should be till the end of this year.
=> Add Alpine Linux into Package Managers section

src/cli_utils.rs, src/config.rs, src/language/language_type.rs, src/language/syntax.rs, src/utils/fs.rs
And the ones not deemed feasible were officialy allowed so folks running
`cargo clippy` should see no warnings.
As `clippy` isn't always perfect and sometimes is a matter of taste, please feel free to make the modifications right away in this PR or close outright in case it's not desired.
I would have wanted to enable clippy in CI but didn't want to risk breakage or overstep 😅.
=> Fix all feasible clippy issues

src/cli.rs, src/cli_utils.rs, src/main.rs
Fixes #605 
Help text is a good bikeshed topic.
Although it may make sense to avoid searching for embedded languages entirely to maybe gain some performance when running with `--compact`, I left it as an output flag at first to avoid potential counting differences around edge cases.
=> Implement compact output feature (#605)

languages.json
[ocamllex and ocamlyacc](https://caml.inria.fr/pub/docs/manual-ocaml/lexyacc.html) are standard parts of the OCaml language distribution and used in compiler prototyping quite a bit.
This was just a one-line addition to `languages.json`.
I had previously added some test data that I checked using the updated binary, but realized that it broke the automated testing since it violated the one file per language structure of the tests directory.
=> ocamllex and ocamlyacc

languages.json, tests/data/gml.gml
GameMaker Language (more commonly referred to as GML) is the scripting language used with [GameMaker](https://www.yoyogames.com/gamemaker), a software for game development. Over the years there have been various iterations of GML (none with specific versions or names), but the changes between them do not alter the syntax enough to cause discrepancies with the support added in this PR.
=> Adds support for GameMaker Language (GML)

languages.json
The term “Lisp” refers to a family of languages including Common Lisp, Emacs Lisp, Clojure, Arc, LFE and the entire Scheme family. While Common Lisp is an important member, it is neither the first nor the only one. It is incorrect to refer to Common Lisp as just Lisp, especially as `tokei` also supports other Lisp dialects like Scheme and Emacs Lisp.
=> Change display name of Lisp to Common Lisp

languages.json
The de-facto standard build facility for Common Lisp, [ASDF](https://common-lisp.net/project/asdf/), uses files with the extension `.asd`. These files are the equivalent of a `Cargo.toml`, but are written in Common Lisp. See [the ASDF manual](https://common-lisp.net/project/asdf/asdf.html#Defining-systems-with-defsystem) for more information.
=> Add .asd file extension for Common Lisp

src/cli_utils.rs
Right now, if you specify `--compact --files` on the command-line, the language headers are compacted (i.e., they don't show sub-language sub-totals); however, individual files do still have sub-language breakouts. This change will suppress file sub-language sub-totals for individual files if the `--compact` flag is given.
=> Apply --compact output to --files

build.rs, src/cli.rs, src/input.rs, src/language/embedding.rs, src/language/language_type.rs, src/language/language_type.tera.rs, src/language/mod.rs, src/language/syntax.rs, src/stats.rs, src/utils/ext.rs, tests/embedding/file_triggeringprincipal_frame_1.html
Fixes #616 
This runs the embedding regexes once per line, and caches their results. The state machine then only tries to look up results by the index.
This also adds a test suite dedicated to embedding, containing only one test file, lifted from the firefox 85 codebase. This is done since adjusting the existing html test to reproduce some problems seemed more complicated.
As a side effect of these changes, counting has become more accurate around embedding (e.g. tokei preciously did not detect javascript at all in the included embedding test), so the precise behavior is expected to differ from the current master.
There are a few more miscounting issues lurking in there, but they seem to be preexisting. Eventually the last commit that simplifies the embedding test should be reverted.
=> Cache embedding regexes

src/cli.rs, src/language/language_type.tera.rs
Hi,
As written in issue #660, there is an inconsistency between the help message about `--languages` and actual output.
So I tried to fix them by adding language extensions to the output (because it seems more useful for me).
But I wonder how the output should be arranged. Currently I'm using whitespace as a separator, but is it preferred to be printed in other styles like comma-separated?
=> Add extensions output for --languages options

README.md
The cargo command when run with cargo install --git https://github.com/XAMPPRocky/tokei.git
fails as there are multiple packages with binaries inside the project. For a particular package,
we'd have to add the name of the package, hence adding tokei
Fixes: #769
=> Cargo install throwing issue during installations

languages.json
Add support for `.hcl` extension used by terragrunt
https://terragrunt.gruntwork.io/
https://github.com/gruntwork-io/terragrunt
https://terragrunt.gruntwork.io/docs/getting-started/configuration/#formatting-terragrunthcl
=> Support terragrunt hcl extension for HCL language

src/cli_utils.rs, src/language/mod.rs, src/stats.rs, src/utils/fs.rs
There's also a deprecated function that I didn't want to just change but I'll point it out... in `language/synatx` line 94 you use the `byte_classes` method on the `AhoCorasickBuilder` but apparently [that either doesn't do anything anymore or won't shortly](https://github.com/BurntSushi/aho-corasick/issues/57).
=> Fix clippy warnings

languages.json, tests/data/ksh.ksh
Hello,
this commit adds Korn shell to the list of supported languages.
It's default shell in OpenBSD now  https://man.openbsd.org/ksh
thanks.
=> add Korn shell to supported languages

README.md
Hi, I wrote a small tool that can parse `tokei -o json`, use like this `tokei -o json | tokei-pie` then generate a sunburst chart, displaying it by opening a tab in the browser. It is interactive, you can click around the sectors to see the code lines reactively.
It parses `tokei`'s json output so this feature do not touch tokei's code at all.
I think it is handy working with tokei. So I think it may interest other tokei users, so I open this PR.
I know it may be rude for opening a PR to just promote myself's project like this, I totally understand if you don't want to accept this, you can just close it if so. :D
https://github.com/laixintao/tokei-pie
=> update readme: add tokei-pie in related tools.

src/language/syntax.rs
Fixes #766 
I pulled a basic set of decently large repos to test these changes against since there aren't benchmarks and I didn't want to make this change without knowing it wouldn't regress performance too much. I compiled a binary from `master` named `master` as well as one from this branch named `removed` and ran
```console
$ hyperfine --warmup 5 --style none --export-markdown /dev/stdout --parameter-list repo cpython,linux,node,rust,TypeScript './master {repo}' './removed {repo}'
```
from there I restructured things into the following table (keeping only the mean with std dev)
| Repo | `master` (ms) | `removed` (ms) |
| :--- | ---: | ---: |
| `cpython` | 134.1 ± 3.5 | 133.7 ± 2.3 |
| `linux` | 1448.7 ± 21.4 | 1493.6 ± 6.1 |
| `node` | 897.4 ± 3.7 | 897.8 ± 9.6 |
| `rust` | 156.8 ± 4.1 …
=> Remove deprecated aho corasick `.byte_classes(false)` toggle

src/language/language_type.rs, src/stats.rs
Fixes #859 
It looks like the blobs when getting stats for jupyter notebooks were getting added as children, but not being added to the root count, so this change simply adds them to the root count as well
=> Add blobs to the totals for jupyter

fuzz/Cargo.lock, fuzz/fuzz_targets/parse_from_slice.rs
It looks like there was an additional option added to `Config` that wasn't updated in the fuzzing harness as well.
I believe this could be caught in CI by adding a step that just runs `cargo check` on each of the fuzz targets. If you would like then I would be open to adding that in as well, but it can be in a separate PR instead
I've started running the fuzzing suite to check for panics on top of this PR and #865 's changes, so we'll see if it turns up anything else
=> Add missing field to `Config` in fuzz harness

Cargo.lock, Cargo.toml, src/input.rs, src/language/languages.rs
Closes: #771 
This PR attempts to fix a couple of issues with the `--output` `--input` flags. The implementation is a breaking change from the old format as described below.
Before serializing the output an extra `Total` count was added in while deserializing did not account for this and would try to parse `Total` as a `LanguageType`. This was one cause of the deserialization error
Serializing previously converted the top level of `LanguageType`s stored in the map to a `String` using `.to_string` before serializing (I'm assuming to get a `String` so that it could be stored with `"Total"`). This differs from how the `LanguageType` would normally get serialized using the `Debug` implementation causing a mismatch when trying to deserialize. E.g. `LanguageType::Bash` with `.to_string()` would …
=> Fix input output mismatch

Cargo.lock, Cargo.toml, src/cli.rs, src/cli_utils.rs, src/config.rs, src/input.rs, src/language/embedding.rs, src/language/language_type.rs, src/language/language_type.tera.rs, src/language/languages.rs, src/language/mod.rs, src/language/syntax.rs, src/main.rs, src/stats.rs, src/utils/ext.rs, src/utils/fs.rs
Upgrades to clap version 3, this one uses the builder method, although I feel the derive version may be better suited here. Additionally, it fixes several lints reported by clippy.
I ran `cargo test` and it passed successfully, is there anything else that should be done?
=> Clap v3 + clippy fixes

src/language/languages.rs
Fixes issue where child languages are not included in the global total.
Before (a6c31a10bc8df7e1a659a7decc4d6d9d43031ddf):
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Rust                    4         1490         1066          208          216
|- Markdown             4          754            0          569          185
(Total)                           2244         1066          777          401
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total                   4         1490         1066          208          216 …
```
=> Summarise language before adding to total

languages.json, tests/data/fennel.fnl
Added support for the [Fennel](https://fennel-lang.org) programming language.
Created a test case file (`tests/data/fennel.fnl`) and added the necessary language information (comments, quotes, extensions) in the `languages.json` file.
I built and tested `tokei` (release build) on my machine (M1 MacBook Pro 13") and it returned the expected values.
=> Fennel support

languages.json
Add support to Autoit scripting language
something about this language is the multiline comment Keyword can also comment out with ';' but I was not sure how can I add this in language json...
```autoit
#include <MsgBoxConstants.au3>
#comments-start
MsgBox($MB_SYSTEMMODAL, "", "This won't display ")
MsgBox($MB_SYSTEMMODAL, "", "nor will this.")
#comments-end
; #cs <- here we commented multiline comment keyword...
MsgBox($MB_SYSTEMMODAL, "", "This will display if '#cs/#ce' are commented out.")
; #ce <- here we commented multiline comment keyword...
```
=> Add Autoit scripting language

languages.json
The standard #!/usr/bin/env is documented for Groovy [1] so add the
match for this.
[1] https://groovy-lang.org/syntax.html#_shebang_line
=> Add env match for Groovy

src/sort.rs
Hello there! This PR removes the usage of the `to_lowercase` method in the `sort` module. I noticed that its goal was to perform case-insensitive pattern-matching, but it unfortunately requires an allocation (due to the `String` return type). The same goal may be achieved through the `eq_ignore_ascii_case` method, albeit with chained `if` conditions rather than a single `match` expression. The upside is that we no longer require the short-lived allocation.
I must note that `--sort code` and `--sort CoDe` (for example) will both still work. However, behavior will change if we give an invalid item such as `--sort hello`. Observe that the `else` block will consume all other cases. Hence, the printed error will exactly copy the incorrect input.
```
$ tokei ... --sort hello
Unsupported sorting …
```
=> Perf: prefer non-allocating, case-insensitive string comparisons

languages.json, tests/data/vhdl.vhd
VHDL 2008 introduced C-style delimited comments.
They are described in section [15.9 Comments](https://faculty-web.msoe.edu/johnsontimoj/Common/FILES/VHDL_2008.pdf#page=248)  of IEEE 1076-2008 (IEEE Standard VHDL Language Reference Manual).
=> add multi_line_comments to VHDL

languages.json, tests/data/m4.m4
This is necessarily kind of fuzzy because m4 supports _changing_ the comment character with the [changecom](https://www.gnu.org/software/m4/manual/html_node/Changecom.html) macro, and `dnl` isn't _really_ a comment (because parenthesis are still matched inside it), but it's a start.
This is on #316 so presumably other people are also interested in it.
=> add m4 language definition

src/language/language_type.tera.rs
Fixes #934
This PR allows to cover versioning of language executables, like it can happen for Python. Currently there is `python`, `python2` and `python3` in this language env. Could just add `python2.7`, but we should add new env item for each new Python version, like `python3.4`, `python3.10`, etc. 
This soon may be somewhat cumbersome, so there is a proposition just to match using `starts_with` which should cover such all things. Main drawback is that it could cover things like `pythonxxx`, but not sure if that's a very big problem.
---
It's merely my second touch of **rust** at all (not mentioning the tera), so if there would be some better way to handle that, I'd love to hear that.
=> [issue_934] from_shebang tera function uses starts_with

languages.json, tests/data/puppet.pp
Add support for counting lines in [Puppet manifests](https://puppet.com).
Note that some Pascal files do use the `.pp` file extension (although I think `.pas` is more common in the wild); I suspect that Puppet is probably more common than Pascal, so it's probably a fair tradeoff to drop the second-most-common pascal extension.
=> add Puppet to tokei; steal .pp from Pascal

README.md, languages.json
A dialect of Lisp that's embedded in Python.
More info about the language:
https://hylang.org/
=> Add Hy support

README.md
Readme.md linked to the announcement of version v12.0.0 for a comparison to other implementations when it is actually part of the v11.0.0 announcement.
=> Fix link to speed comparison in README.md

languages.json, tests/data/hicad.mac
Hi @XAMPPRocky
This is for a closed source language specific to a CAD program from [ISD Germany](https://www.isdgroup.com/).
The point in adding this is, I have to maintain a lot of legacy code, and this tool would help me alot.
.mac is very generic I know, but since no one else claimed it yet, it would at least serve my purpose 😄
btw. I added a testfile but have no idea how to test with it, other than well using it, which works.
=> Add HiCAD to languages.json

languages.json, tests/data/Smalltalk.cs.st
Added support for the smalltalk programming language.
=> Add support for smalltalk

Cargo.lock, Cargo.toml, src/config.rs
`~/Library/Application Support` is an utterly inconvenient location for macOS users. Most CLI tools follow the `XDG conventions` on macOS as well. Replace the `dirs` crate with the `etcetera` crate to use it on macOS. Config locations for other platforms are unchanged.
Disclaimer: I've recently become a maintainer of the etcetera crate. AFAIK, it is the only crate that allows using XDG on macOS, while also supporting Windows.
=> Use XDG conventions on macOS too

.gitignore, Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs
Now it seems like this:
```
──────────────────────────────────────────────────────────────────
| Language                           Extensions                  |
|────────────────────────────────────────────────────────────────|
| ABNF                               abnf                        |
| AWK                                awk                         |
| ABAP                               abap                        |
| ActionScript                       as                          |
| ...                                ...                         |
──────────────────────────────────────────────────────────────────
```
> `EmojiCode` is treated differently, since emojis are usually rendered as two characters, so I add a `\u+200b` to render it correctly.
=> Update `--languages` Output Format

languages.json
This PR fixes the following points for linker scripts support:
- `.ld` file extension is very common ([e.g. Linux kernel](https://github.com/torvalds/linux/blob/master/arch/x86/boot/setup.ld)).
- `//` line comment is now allowed for linker scripts. [The specification](https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_chapter/ld_3.html) only mentions `/*` and `*/` as comments. And I confirmed ld actually causes an error as follows.
```
error: kernel.ld:4: unknown directive: //
>>> // hoge
>>> ^
```
=> Fix LD Script language data

src/cli_utils.rs
Fixes #805
Changed the language names to be coloured in magenta, so it can work in Light mode (white background).
BEFORE
AFTER:
=> fixed language names not showing when in Light mode (light background

languages.json
This PR:
• Adds `.mts` and `.cts` to the TypeScript extensions array
=> Update TypeScript language

languages.json, tests/data/chapel.chpl
This commit adds support for [Chapel](https://chapel-lang.org/).
Per [Chapel's documentation] it supports C-style comments and single or double quoted strings.
[Chapel's documentation]: https://chapel-lang.org/docs/language/spec/lexical-structure.html
=> Add support for Chapel

languages.json, tests/data/PKGBUILD
#888 
> Support for Arch Linux PKGBUILD files
I wanted it too so here it is.
"PacmanMakepkg" could be renamed either "Pacman" or "Makepkg" if you believe the name is too long.
=> Add arch's PKGBUILD files

languages.json, tests/data/razor.cshtml, tests/data/razorcomponent.razor
- Adds missing `C#` comments
- Adds missing `C#` quotes
- Adds support for Razor Components (`.razor` files)
Blocks like this will now be counted correctly:
```razor
@{
// foo
string foo = "bar";
/*
* bar
*/
string bar = "foo";
}
```
Razor docs: https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-7.0
=> Fix Razor support

README.md, languages.json, src/language/embedding.rs, src/language/language_type.rs, src/language/language_type.tera.rs, src/language/syntax.rs, tests/data/linguafranca.lf
This adds support for the [Lingua Franca](https://www.lf-lang.org/) language (LF). LF is a coordination language that embeds fragments of another language (eg Rust, C, Python). For that reason tokei's embedded language feature is very valuable. Here's a sample output when run on [this repo](https://github.com/lf-lang/benchmarks-lingua-franca/):
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
...
Lingua Franca          87         8964         4379         2567         2018
|- C                   30         2451         1923          307          221
|- C++                 24         2120         1659          238          223
|- Python               1           14           14 …
```
=> Add lingua franca language

.gitignore, src/cli.rs, src/input.rs, src/language/language_type.rs, src/language/syntax.rs, src/utils/fs.rs
- Remove some unnecessary reference.
- Change those `expect()` into `unwrap_or_else(|| panic!())`. (see [Clippy-expect_fun_call](https://rust-lang.github.io/rust-clippy/master/index.html#/expect_fun_call))
=> Remove Unnecessary Refs

languages.json, tests/data/Snakefile
This PR adds support for [Snakemake](https://snakemake.readthedocs.io), which uses a Python-like syntax.
=> Adding support for Snakemake

languages.json
Python uses `.pyi` files for [type stubs](https://typing.readthedocs.io/en/latest/source/stubs.html), type annotations that live outside the main source code. While these files are not executed, they contain valid python and are written and read as such by humans and tools such as type checkers and IDEs.
On [typeshed](https://github.com/python/typeshed), the main repository for type stubs in python:
**before**
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INI                     1            7            7            0            0
JSON                    4          217          217            0 …
```
=> Support .pyi python files

languages.json, tests/data/lalrpop.lalrpop
[lalrpop](https://github.com/lalrpop/lalrpop) is a parser generator metalanguage for the Rust language.
- Add an entry for LALRPOP in `languages.json` file.
- Add test for LALRPOP file.
=> feat: add support for LALRPOP

README.md, languages.json, tests/data/openscad.scad
OpenSCAD is a software for creating solid 3D CAD objects. 
SCAD stands for "Scripted CAD", where CAD is an acronym for "Computer-Aided Design".
- https://github.com/openscad/openscad
- https://openscad.org/documentation.html#language-reference
=> Add OpenSCAD

src/cli.rs, src/config.rs
Previously, setting `hidden = true` in the config file would have no effect. Now it is properly read.
Fixes: #1092
=> fix: read hidden from config file

src/cli_utils.rs, src/main.rs
Now if --files argument is found it will sort by default alphabetically the name of the files. If --sort argument is also provided (for example tokei --files --sort blanks), the sorting for files will be ignored and it will only sort by given argument.
Should fix https://github.com/XAMPPRocky/tokei/issues/1053
=> Fixed --files argument to sort alphabetically

src/language/language_type.rs, src/language/language_type.tera.rs
Currently, `LanguageType::from_shebang()` uses `BufReader` and `BufRead::read_line()` to fetch the first line of the file.
- `BufReader::new()` allocates 8 KiB of buffer by default
- `BufRead::read_line()` can end up reading the entire file
A typical shebang line ranges from 10 to 30 characters (e.g. `#!/usr/bin/env python3` is only 22B),
and it is *very* unlikely the file contains a valid shebang syntax if we don't find a newline character within the first few dozens of bytes.
This PR modifies the code so that it only reads the first 128B of the file, into the fixed sized `u8` array, without involving the unnecessary `BufReader` and `String`.
=> Optimization: Read only first 128B from the file when searching for shebang

README.md, languages.json, tests/data/cil.cil
Common Intermediate Language is a format of SELinux policy source
=> feat: add SELinux CIL policy source files

README.md, languages.json, tests/data/hledger.hledger
Hello,
I added the support for hledger (plain text accounting).
I noticed there are some differences between the comment syntax between "hledger" and "ledger", so I limited the extension to ".hledger", which should be hledger only.
hledger: https://hledger.org/1.34/hledger.html?highlight=extension#comments
ledger: https://ledger-cli.org/doc/ledger3.html#Transactions-and-Comments
=> Add hledger support

languages.json
This adds the extension `.fpp` to the Modern Fortran language, which is associated with [Fypp](https://fypp.readthedocs.io/en/stable/fypp.html) metaprogramming files for Fortran. These files have the same syntax as usual free-form Fortran except for the possibility of a `#:` leading character for the "fypp part." Such lines should be considered part of the normal code line count anyway, so no other changes to `languages.json` are needed.
=> Add fypp extension `.fpp` to `languages.json` for Modern Fortran

languages.json, tests/data/plantuml.puml
This PR adds support for the PlantUML diagramming language.
=> Add PlantUML support

Cargo.toml, src/cli.rs, src/cli_utils.rs, src/consts.rs, src/lib.rs, src/utils/ext.rs
Summary of fixes:
* ~~Added *empty* `json` feature and included in `all`~~
* Removed unnecessary `Cli.verbose` property
* Removed unnecessary `NumberFormatStyle.all()` method
* Added doc strings for pub constants in `src/consts.rs`
* Exported `self::consts::*` in `src/lib.rs`
* Removed unused `AsciiExt.is_not_line_ending_whitespace()` method
=> Fix issue #1141

Cargo.toml
Cargo makes redundant features for each optional dependency: https://lib.rs/crates/tokei/features#features-dep-implied 
This change hides them. 
I've also bumped edition, since this crate requires a newer Rust anyway (due to [env_logger](https://lib.rs/crates/env_logger/versions)).
=> Disable legacy Cargo features

Cargo.toml
The use of `/` is deprecated, per the Cargo reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
=> Use `OR` operator in Cargo.toml `license` field

README.md, languages.json, tests/data/templ.templ
Hello hello,
I added the support for [templ](templ.guide), which a template language for Go, GitHub recently added support for it, so why not add it to tokei 😄  
File extensions:
- `.templ`
- `.tmpl`
=> Add templ support

README.md, languages.json, tests/data/justfile
This adds support for [justfile](https://github.com/casey/just).
Just supports recipes that contain a shebang, but unfortunately it's being interpreted as a comment line and I don't see a way to resolve it within Tokei.
```just
do-something:
#!/usr/bin/env node
console.log('im running in node')
do-something-else:
echo "regular recipe"
```
Closes #1116
=> Add support for justfiles

languages.json
This PR just adds `fsti` to the list of extensions for F*. (while `fst` files are for implementations, `fsti` files are for interfaces)
=> Add missing extension `fsti` for F*

src/cli.rs
The new value parser introduced in [1] did not parse the option into a `Format`, but rather into a string, thus breaking alternative output formats, as a different type was expected.
Fixes: https://github.com/XAMPPRocky/tokei/issues/1170
[1]: 9627a24c9c53ebb5ded0c297d9221b8d0d331c09 (Fix cargo audit issues (#1137))
---
N.b: Should this be reported as a bug somewhere? Type errors being propagated to runtime sounds like something `clap` should not do.
=> Fix alternative output formats

languages.json
This really can't be claimed by a single language, unless it's an attempt at a "generic" config file format.
This should resolve issue #1000 (as reported by myself).
=> Remove 'conf' extension from the Bitbake config.

languages.json, tests/data/roc.roc
Add support for the [Roc language](https://www.roc-lang.org/)
=> Add support for `Roc` language

languages.json, tests/data/eight.8th
This PR adds support for the [8th language](https://8th-dev.com/)
=> Add support for 8th language

src/language/embedding.rs
Also fixes an `elided_named_lifetimes` warning in one place.
=> Relax lifetime constraints in language::embedding

languages.json
Add support for [Avalonia XAML](https://docs.avaloniaui.net/docs/basics/user-interface/introduction-to-xaml), a dialect of XAML with its own file extension.
Closes [issue](https://github.com/XAMPPRocky/tokei/issues/672)
=> Add Avalonia Xaml support
