src/main.rs
Changed row from const to static and moved outside main function to be global to address error.
=> Fixed E0106 error on windows

.travis.yml
Since this is under an open source license you get access to Travis-CI for free.  Follow steps 1 and 2 at http://docs.travis-ci.com/user/getting-started/ so that when there is a commit or PR the code is compiled to see if there are any errors to make life easy.  Accepting this pull request after that is done should generate the first automated build.
=> Added Travis to setup automated build testing of commits and PRs

src/main.rs
Just found the #17 PR, so here are a few more modern Fortran extensions.
=> More modern fortran extensions

src/main.rs
This add the following
- Lua language
- `.hxx` extension for C++ headers
=> More languages

src/main.rs
before:
```
$ ls
Makefile  hello.py
$ tokei .
Language            Files        Total       Blanks     Comments         Code
Python                  1            4            2            0            2
Total                   1            4            2            0            2
```
after:
```
$ ~/work/tokei.hhatto/target/release/tokei .
Language            Files        Total       Blanks …
```
=> fixed skipped Makefile

src/language.rs, src/main.rs
support Protocol Buffers, Vim script, zsh.
Thanks.
=> Support more language

src/fsutil.rs, src/main.rs
This time hopefully against the current revision :smile:
=> another two clippy warnings fixed

src/lib/stats.rs
=> Avoid panicking on non-character-boundary inside string slice

src/main.rs
Just pulled two if-statements together and removed one needless `&`. This is really awesome code, btw. :+1:
=> fixed another two clippy warnings

CHANGELOG.md, CONTRIBUTORS.md, README.md, src/lib/language/language_type.rs, src/lib/language/languages.rs
I followed the [official extensions](https://github.com/KhronosGroup/glslang#execution-of-standalone-wrapper) for this.
=> Add GLSL support

Cargo.lock
Contains https://github.com/serde-rs/json/pull/172 which fixes #83.
=> Update to serde_json 0.8.4

languages.json
This adds support for PureScript (http://purescript.org).
https://github.com/purescript/documentation/blob/master/language/Syntax.md#comments
=> Added support for PureScript

README.md
Added languages that weren't mentioned in the README - based on the CHANGELOG commit made recently: https://github.com/Aaronepower/tokei/commit/6cf2d65725236e2d73a094cc4e2d024282118cfa.
=> Updated list of supported languages

languages.json
Greetings from Finland! 👋
I've been a long time fan of tokei but unfortunately it doesn't recognize my fish scripts. This PR adds a language definition for the fish shell.
If I understood correctly, you don't have to do much else to support a language. Please let me know if there's any issues with this PR.
Cheers!
=> Add support for the fish shell

Cargo.lock, languages.json
Added support for various little languages. I had to update the `Cargo.lock` to get it to build.
=> added hamlet, cassius, lucius, cabal, nix, happy, alex, and madlang support

README.md
Added method of installation using Nix package manager
=> Added another installation method

README.md, languages.json
Adds support for [Processing](https://processing.org/) (`.pde`) files.
=> Added Processing language support

README.md, languages.json, tests/data/html.html, tests/data/xtend.xtend
Adds [Xtend](http://www.xtend-lang.org) support.
=> Add Xtend support

Cargo.lock, Cargo.toml, src/language/language_type.hbs.rs, src/language/languages.rs
=> bump ignore to 0.3, rayon to 0.9, handlebars to 0.29, hex to 0.3

Cargo.lock, Cargo.toml, src/input.rs, src/language/languages.rs
=> Bump serde_cbor to 0.8

README.md
=> Fix broken copyright link in ToC

README.md
Hi,
I'm maintaining the FreeBSD [tokei port](https://www.freshports.org/devel/tokei). It'd be nice if it could be mentioned in the README.
Thanks!
=> Add FreeBSD install instructions

Cargo.lock, Cargo.toml
=> deps/env_logger: 0.5.0-rc.2 → 0.5.0

Cargo.lock, Cargo.toml, build.rs
=> deps: update handlebars to 0.30

README.md, build.rs, languages.json, tests/data/meson.build
Fixes: https://github.com/Aaronepower/tokei/issues/168
=> add support for Meson

Cargo.lock, Cargo.toml
=> deps: update handlebars to 0.31

Cargo.lock, Cargo.toml
=> deps: update ignore to 0.4

languages.json, src/language/language.rs, tests/data/scheme.scm
=> Fix typos. Add Scheme.

languages.json
=> supported vue files

languages.json, tests/data/zig.zig
https://github.com/zig-lang/zig
=> Add support for zig

README.md, languages.json
https://github.com/mint-lang
https://gdotdesign.gitbooks.io/mint/content/
:)
=> Add Mint language support

Cargo.lock, Cargo.toml
=> deps: update handlebars to 0.32

languages.json, tests/data/elvish.elv
=> Added Elvish shell.

languages.json, tests/data/kakoune_script.kak
=> Added Kakoune script.

languages.json
https://reasonml.github.io/
https://github.com/github/linguist/blob/14fcd75773a49637b644ca60028ff245f617595f/lib/linguist/languages.yml#L3879
=> Add ReasonML as alternative syntax of OCaml

README.md, languages.json, tests/data/hcl.tf
Adding [HCL](https://github.com/hashicorp/hcl) language support.
=> add HCL/Terraform support

README.md, languages.json, tests/data/vb6_bas.bas, tests/data/vb6_cls.cls, tests/data/vb6_frm.frm
https://en.wikipedia.org/wiki/Visual_Basic
=> Added VB6 Support

Cargo.lock, Cargo.toml
=> deps: update handlebars to 1

languages.json, tests/data/logtalk.lgt
Added support for the Logtalk programming language (https://logtalk.org/).
=> Added support for Logtalk

README.md, languages.json, tests/data/solidity.sol
Add support for the [Solidity programming language](https://solidity.readthedocs.io/en/v0.5.4/index.html)
=> Add solidity support

README.md
Add tokei_rs repository link. See #310.
=> add tokei_rs repository link (#310)

languages.json, tests/data/postcss.pcss
Resolves #314 
I'm fairly certain this is all that needs to be done;
it seems to work on my machine.
=> Add PostCSS to languages

languages.json, tests/data/pony.pony
This adds some basic support for [pony](https://www.ponylang.io/)
=> add Pony support with test

languages.json
See https://coffeescript.org/#jsx for details.
=> Add .cjsx as a CoffeeScript extension

languages.json, tests/data/powershell.ps1
=> Add PowerShell support

tests/data/c.c, tests/data/sql.sql
This is my first contribution, so please let me know if there is anything I need to correct, thanks!
=> Added tests for C and SQL

languages.json, tests/data/thrift.thrift
https://en.wikipedia.org/wiki/Apache_Thrift
=> Add thrift language

tests/data/go.go
=> Add basic test for Go language

src/cli_utils.rs
Resolves #347.
This PR truncates language names that do not fit into the language column, cutting the string off with a `|`. Worth considering would also be to truncate the language name the same way long file paths are being truncated where as this is currently doing the exact opposite
This also fixes a panic that can occur in debug when a permission error happens for a language that doesn't fit the column, the subtraction then would underflow that was used previously.
Example output:
```
C#                      4          350          303            4 …
```
=> fix too long language names misaligning table output

languages.json, tests/data/flatbuffers.fbs
Adds support for FlatBuffers schemas (a serialization library similar to Protocol Buffers), documented here: https://google.github.io/flatbuffers
=> Add support for FlatBuffers

src/cli.rs
I assume mentioning what kinds of patterns are supported could be done somewhere else, it's not really fitting for this help-page. Maybe man-pages or the wiki or so.
=> Explain main input argument and --exclude a bit better

languages.json, tests/data/arduino.ino
Fixes #474
Example output:
```
Arduino C++             5          387          297           60           30
Autoconf                2           21           14            3            4
C Header               23         2294         1597          439          258
C++                    29         2925         1966          510          449
Makefile                2          247          145           48           54
Markdown                2           97           97            0            0
Shell                   2           53           42 …
```
=> Add Arduino support

src/utils/fs.rs
Reduce the number of option checks by not distributing it at first.
Not sure if this helps improve the performance.
```
Tokei Benchmarking Tool
The use of this tool requires tokei, and hyperfine to be installed and available in your PATH variable.
Please enter the path you would like to benchmark:
hyperfine 1.9.0
old tokei: tokei 11.0.0 compiled with serialization support: cbor, json, yaml
Compiling tokei v11.0.0 (/home/ivan/src/pickfire/rs/tokei)
Finished release [optimized] target(s) in 50.01s
Benchmark #1: target/release/tokei
Time (mean ± σ):       5.4 ms ±   0.6 ms    [User: 5.7 ms, System: 4.4 ms]
Range (min … max):     4.8 ms …  15.4 ms    510 runs
Warning: Command took less than 5 ms to complete. Results might be inaccurate.
Warning: Statistical outliers were detected. Consider …
```
=> Check option in outer loop

languages.json, tests/data/headache.ha
Added Headache programming language.
https://github.com/LucasMW/Headache  Headache source tree.
https://github.com/LucasMW/Headache/wiki Headache documentation
=> Added Headache Program Language

languages.json, tests/data/gohtml.gohtml
**Details** https://golang.org/pkg/html/template/
=> Add Go HTML template support

README.md, languages.json, tests/data/tsx.tsx
* Follows the JSX and Javascript separation
* Separate TSX and Typescript for clearer stats
* Add TSX test
=> Separate TSX and Typescript Support

CONTRIBUTING.md, tests/data/rust.rs
Updated Rust test to have lifetimes, to catch this edge case.
#514
=> Added Lifetimes edge case to Rust example

README.md, src/config.rs
Support home directory in from_config_files
=> Support home directory in from_config_files

README.md, languages.json, tests/alloy.als
Alloy is an open source language and analyzer for software modeling.
Homepage: http://alloytools.org/
=> Add Alloy language

languages.json
Looks like some keys were added twice to certain objects in the languages.json.
=> Remove duplicate keys from some objects in languages.json

src/input.rs
=> Remove duplicated 'json' from --output

src/cli_utils.rs, src/input.rs, src/language/languages.rs
=> Add summary information to output formats

languages.json, tests/data/livescript.ls
LiveScript is a language which compiles to JavaScript.  (http://livescript.net/)
=> Add LiveScript to languages.json

languages.json, tests/data/Tera.tera
As Tera is a templating language which can be used not only for HTML, is this the best way?
=> add Tera templating language

languages.json, tests/data/ttcn.ttcn3
http://www.ttcn-3.org/index.php/downloads/standards
=> Add support for TTCN-3

README.md, src/cli.rs, src/config.rs, src/utils/fs.rs
=> Make --no-ignore imply all other --no-ignore- flags

languages.json, tests/data/gleam.gleam
Hiya!
Teaching Tokei to spot [Gleam](https://gleam.run/).
Thanks :)
=> Add support for the Gleam language

languages.json, tests/data/jsonnet.jsonnet
Jsonnet is quite a minimal language, let me know if the test needs to be more detailed.
=> Add jsonnet to language list

README.md
=> Add missing language to language list

src/cli_utils.rs
Bascially the implementation as per this instruction:
https://github.com/XAMPPRocky/tokei/pull/685#issuecomment-752112937
It's hard to not value all your effort by making this indeed simple PR. Thanks for the nudge :D, I am glad I could become a contributor to `tokei`!
=> Fix for #684

languages.json, tests/data/pug.pug
=> Add support for pug

Cargo.lock, Cargo.toml, src/config.rs
Fixes #669 
Replaces dirs dependency with dirs-next
=> Replace dirs with dirs-next

languages.json, tests/data/kvlanguage.kv
Hi there,
Thanks for the great tool.  Python developers who write GUIs using the Kivy framework define much of the UI in .kv language files (.kv).  I've added the language definition for kv lang to the languages.json file and added a test file that passes just fine.  
You can read more about kv lang here: https://kivy.org/doc/stable/guide/lang.html
Thanks again,
Roland
=> added support for kvlang - https://kivy.org/doc/stable/guide/lang.html

README.md
Should help pre-empt questions like #333
=> README.md: describe .tokeignore file

languages.json, tests/data/open_policy_agent.rego
Not quite sure if I need an issue before adding support but it'd be awesome to have some support for the Open Policy Agent
=> add OpenPolicyAgent support and test

README.md, languages.json, tests/data/mlatu.mlt
Adds Mlatu language
https://github.com/brightly-salty/mlatu
=> Add Mlatu language

README.md, languages.json, tests/data/factor.factor
Hi,
Adding support for the Factor language.
https://github.com/factor/factor
https://factorcode.org
=> Add support for the Factor language.

languages.json, tests/data/lolcode.lol
This PR adds [LOLCODE](http://www.lolcode.org/) language support to tokei. 
Yes, I really need this, as I'm working on a project involving this ~~horrid~~ awesome language :-)
=> Add LOLCODE support

README.md, languages.json, tests/data/ats.dats
Adding language support and test spec for [ATS](http://www.ats-lang.org).
- #159
=> Language Support for ATS

languages.json
Signed-off-by: Maciej Barć <xgqt@riseup.net>
=> languages.json: Racket - add scrbl extension and racket env

languages.json, tests/data/unison.u
Adding Unison programming language with test file.
=> Add support for Unison 

README.md, languages.json, tests/data/poke.pk
Support GNU Poke
https://www.gnu.org/software/poke/
https://www.jemarch.net/poke
=> Add Poke support

languages.json, tests/data/nextflow.nf
Nextflow
https://nextflow.io/
Nextflow is a bioinformatics workflow manager. An extension of the Groovy language.
=> Add support for Nextflow

README.md, languages.json, tests/data/cuda.cu
add support for CUDA language. (almost same as c/c++, but extension is `.cu`)
=> add support for CUDA language

CONTRIBUTING.md
I fixed some typos and links and added small enhancements :)
It would be awesome if you could release a new version btw, because a lot of changes were done since the last release on 12.01.2021 👍🏽
=> Enhance CONTRIBUTING.md

src/cli.rs
Fixes #https://github.com/XAMPPRocky/tokei/issues/878
=> input will default to the current directory

README.md, languages.json, tests/data/shaderlab.shader
This adds support for Unity3D shaders.
=> Add shaderlab support

languages.json
https://www.typescriptlang.org/docs/handbook/esm-node.html
=> Add Common JS file extension (cjs)

src/config.rs
=> fix issue944

README.md, languages.json, tests/data/jq.jq
This adds the [jq language](https://stedolan.github.io/jq/)
* comments: https://github.com/stedolan/jq/wiki/jq-Language-Description#jq-program-structure-and-basic-syntax
* strings: https://github.com/stedolan/jq/wiki/jq-Language-Description#data-types
=> Add support for jq

languages.json, tests/data/redscript.reds
Redscript is a scripting language for Cyberpunk 2077 modding: see [website](https://wiki.redmodding.org/redscript/) and [github repository](https://github.com/jac3km4/redscript).
> As a side note: Redscript closest syntax is Swift, hence its configuration. Also added `///` as valid line comments from its lineage, as this is a language written in Rust.
=> Add Redscript support

CONTRIBUTING.md
This PR removes the duplicate entry in the language data example in CONTRIBUTING.md
=> Fix language data example in CONTRIBUTING.md

languages.json, tests/data/circom.circom
This PR adds support for the Circom zero-knowledge proof DSL.
=> Added language support for Circom

README.md, languages.json, tests/data/slang.slang
Adds support for the shader language Slang.
=> Add language support for Slang

README.md, languages.json
Visual programming language for music and multimedia, for details see:
What is Max? | Cycling '74
https://cycling74.com/products/max
Max (software) - Wikipedia
https://en.wikipedia.org/wiki/Max_(software)
Note: maxpat's are json code, which do not support comments, thus I skipped adding a test file
Thanks a lot for this great piece of software!
=> Add Max support

README.md, languages.json
Hare is a systems programming language designed to be simple, stable, and robust.
https://harelang.org/
=> Add Hare support

README.md, languages.json, tests/data/zokrates.zok
Thank you for building this nice tool!
Language documentation: https://zokrates.github.io/
Comment documentation: https://zokrates.github.io/language/comments.html
There are no strings.
=> Add the ZoKrates language

languages.json
[Luau](https://luau-lang.org/) is Roblox's version of Lua with added types.
=> add luau extension to lua

.github/workflows/publish_image.yaml, Earthfile, README.md
=> GitHub Action to publish docker images

README.md, languages.json, tests/data/gdshader.gdshader
As the title says,add the support of godot shader
=> Support godot shader

languages.json, tests/data/jslt.jslt
[1] https://github.com/schibsted/jslt
---
What is the `blank` flag in languages.json btw?
=> Add support for JSLT

languages.json, tests/data/cangjie.cj
* add cangjie language definitio
* add test file cangjie.cj
=> add cangjie language support (#1127)

README.md, languages.json, tests/data/bicep.bicep
Adds support for the Bicep language.
https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/file
=> feat: add support for bicep

README.md, languages.json, tests/data/tact.tact
More about the language: https://tact-lang.org
• Added an entry in `languages.json`
• Added a test
• Updated README.md
Hope everything's correct here :)
=> feat: add Tact language

src/cli.rs
https://github.com/XAMPPRocky/tokei/issues/1145
=> Fix issue #1145

src/cli.rs
https://github.com/XAMPPRocky/tokei/issues/1145#issuecomment-2306329950
=> Fix issue #1145 (part 2)

README.md, languages.json, tests/data/slint.slint
https://slint.dev/
https://slint.dev/releases/1.3.2/docs/slint/
=> add slint language support

languages.json
SIL is short for Symmetry Integration Language and is developed by Symmetry Investments.
=> Add support for SIL

README.md, languages.json, tests/data/apl.apl
It's—quite literally—"a programming language" :)
=> Add APL support

languages.json
Add DirectX9 effect file extension.
=> Add more extensions for Hlsl

README.md, languages.json, tests/data/bqn.bqn
BQN is an array language in the spirit of APL/J/K; [website here](https://mlochbaum.github.io/BQN/)
=> Add BQN support

languages.json
Adds support for [Virgil](https://github.com/titzer/virgil). Virgil is a programming language designed for building lightweight high-performance systems.
=> Add Virgil

languages.json
Reference: https://www2.lauterbach.com/pdf/practice_ref.pdf
=> Add language definition for Lauterbach PRACTICE Script

languages.json, tests/data/cairo.cairo
This PR adds support for the [Cairo language](https://www.cairo-lang.org/)
=> Add support for Cairo language

languages.json, tests/data/ballerina.bal
This PR adds support for the [Ballerina language](https://ballerina.io/)
=> Add support for Ballerina language

languages.json, tests/data/mojo.mojo
=> add Mojo support (#1107)
